### ISSUE TITLE
CT voice should match the provided utterance's

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/utterance-queue#113]
```
utterance-queue : top-level-unit-tests : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/utterance-queue/utterance-queue-tests.html
8 out of 9 tests passed. 1 failed.
UtteranceQueue: utterance.announcerOptions.voice failed:
voice should match the provided utterance's
myListener@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:263:12
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/TinyEmitter.js:95:17
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/Emitter.js:46:22
handleSpeechSynthesisEnd@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:626:29
step@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:341:14
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/TinyEmitter.js:95:17
before/intervalID<@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:123:17
setInterval handler*before@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:117:25

id: Sparky Playwright Firefox
Snapshot from 5/11/2023, 7:59:01 AM

----------------------------------

utterance-queue : top-level-unit-tests : unbuilt?brand=phet-io
http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/utterance-queue/utterance-queue-tests.html?brand=phet-io
8 out of 9 tests passed. 1 failed.
UtteranceQueue: utterance.announcerOptions.voice failed:
voice should match the provided utterance's
myListener@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:263:12
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/TinyEmitter.js:95:17
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/Emitter.js:46:22
handleSpeechSynthesisEnd@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:626:29
step@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:341:14
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/TinyEmitter.js:95:17
before/intervalID<@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:123:17
setInterval handler*before@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:117:25

id: Sparky Playwright Firefox
Snapshot from 5/11/2023, 7:59:01 AM

----------------------------------

utterance-queue : top-level-unit-tests : unbuilt?ea
http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/utterance-queue/utterance-queue-tests.html?ea
8 out of 9 tests passed. 1 failed.
UtteranceQueue: utterance.announcerOptions.voice failed:
voice should match the provided utterance's
at myListener (http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:263:12)
at TinyEmitter.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/TinyEmitter.js:95:9)
at Emitter.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/Emitter.js:46:22)
at VoicingManager.handleSpeechSynthesisEnd (http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:626:29)
at SpeechSynthesisUtterance.endListener (http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:568:12)

[URL] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1683813541246%2Futterance-queue%2Futterance-queue-tests.html%3Fea&testInfo=%7B%22test%22%3A%5B%22utterance-queue%22%2C%22top-level-unit-tests%22%2C%22unbuilt%3Fea%22%5D%2C%22snapshotName%22%3A%22snapshot-1683813541246%22%2C%22timestamp%22%3A1683814015591%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1683813541246%2Futterance-queue%2Futterance-queue-tests.html%3Fea&testInfo=%7B%22test%22%3A%5B%22utterance-queue%22%2C%22top-level-unit-tests%22%2C%22unbuilt%3Fea%22%5D%2C%22snapshotName%22%3A%22snapshot-1683813541246%22%2C%22timestamp%22%3A1683814015591%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/utterance-queue/utterance-queue-tests.html?ea
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found)
[CONSOLE] enabling assert

id: "Sparky Node Puppeteer"
Snapshot from 5/11/2023, 7:59:01 AM

----------------------------------

utterance-queue : top-level-unit-tests : unbuilt?ea&brand=phet-io
http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/utterance-queue/utterance-queue-tests.html?ea&brand=phet-io
8 out of 9 tests passed. 1 failed.
UtteranceQueue: utterance.announcerOptions.voice failed:
voice should match the provided utterance's
myListener@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:263:12
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/TinyEmitter.js:95:17
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/Emitter.js:46:22
handleSpeechSynthesisEnd@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:626:29
step@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:341:14
emit@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/axon/js/TinyEmitter.js:95:17
before/intervalID<@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:123:17
setInterval handler*before@http://127.0.0.1/continuous-testing/ct-snapshots/1683813541246/chipper/dist/js/utterance-queue/js/UtteranceQueueTests.js:117:25

id: Sparky Playwright Firefox
Snapshot from 5/11/2023, 7:59:01 AM
```

**Comment by zepumph** [comment]
https://github.com/phetsims/utterance-queue/commit/27e4a55d426537943133478dd0ce6619b555c70f should do it!

**Comment by jessegreenberg** [comment]
Thanks!
