### ISSUE TITLE
CT cannot read property addToBack of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/utterance-queue#15]
```
john-travoltage : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/phet-io-wrappers/state/?sim=john-travoltage&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603278869128%22%2C%22timestamp%22%3A1603281540368%7D
Uncaught Error: Cannot read property 'addToBack' of undefined
TypeError: Cannot read property 'addToBack' of undefined
at setElectronStatus (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/john-travoltage/js/john-travoltage/view/ElectronLayerNode.js:86:50)
at electronAddedListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/john-travoltage/js/john-travoltage/view/ElectronLayerNode.js:105:7)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/Emitter.js:60:19)
at PhetioGroup.notifyElementCreatedWhileDeferred (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/tandem/js/PhetioDynamicElementContainer.js:378:32)
at PhetioGroup.setNotificationsDeferred (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/tandem/js/PhetioDynamicElementContainer.js:395:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/tandem/js/PhetioDynamicElementContainer.js:140:16
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/TinyEmitter.js:71:18)
id: Bayes Chrome
Snapshot from 10/21/2020, 5:14:29 AM

----------------------------------

john-travoltage : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/studio/?sim=john-travoltage&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603278869128%22%2C%22timestamp%22%3A1603283482097%7D
Uncaught Error: Uncaught TypeError: Cannot read property 'addToBack' of undefined
TypeError: Cannot read property 'addToBack' of undefined
at setElectronStatus (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/john-travoltage/js/john-travoltage/view/ElectronLayerNode.js:86:50)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/Emitter.js:60:19)
at JohnTravoltageModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/john-travoltage/js/john-travoltage/model/JohnTravoltageModel.js:382:36)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/joist/js/Sim.js:299:22
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/axon/js/Action.js:225:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/joist/js/Sim.js:1002:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603278869128/joist/js/Sim.js:992:12)
id: Bayes Chrome
Snapshot from 10/21/2020, 5:14:29 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, fixed in the above commits.
