### ISSUE TITLE
CT Utterance: alertMaximumDelay tests failed:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/utterance-queue#70]
```
utterance-queue : top-level-unit-tests : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647616024905/utterance-queue/utterance-queue-tests.html
6 out of 7 tests passed. 1 failed.
Utterance: alertMaximumDelay tests failed:
still has it, not stable, not max, 2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647616024905/chipper/dist/js/utterance-queue/js/UtteranceTests.js:135:10)

Utterance: alertMaximumDelay tests failed:
not stable, but past max
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647616024905/chipper/dist/js/utterance-queue/js/UtteranceTests.js:139:10)

id: Bayes Chrome
Snapshot from 3/18/2022, 9:07:04 AM
```

**Comment by zepumph** [comment]
I'm pretty sure this is because bayes get's bogged down and it takes a couple more ms to get past the sleep timing here:

https://github.com/phetsims/utterance-queue/blob/2a4bf3c8d3a3f8a9c0c993d9155d72d3ce0a4e58/js/UtteranceTests.js#L124

Such that the last element in the queue has already been flushed. I added grace, and I will check back in next week to see if that fixed things.

**Comment by zepumph** [comment]
I don't see this anymore on CT. CLosing
